[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# add CanvasSprite for dice
[[patches]]
[patches.pattern]
target = "game.lua"
position = "after"
match_indent = true
pattern = '''
self.shared_seals = {
    Gold = Sprite(0, 0, self.CARD_W, self.CARD_H, self.ASSET_ATLAS["centers"], {x = 2,y = 0}),
    Purple = Sprite(0, 0, self.CARD_W, self.CARD_H, self.ASSET_ATLAS["centers"], {x = 4,y = 4}),
    Red = Sprite(0, 0, self.CARD_W, self.CARD_H, self.ASSET_ATLAS["centers"], {x = 5,y = 4}),
    Blue = Sprite(0, 0, self.CARD_W, self.CARD_H, self.ASSET_ATLAS["centers"], {x = 6,y = 4}),
}
'''
payload = "self.shared_dice = {}"